%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/juan/projects/lab/incflow/tests/vars.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/08/25 13:47:48

%% Initialize variables.
filename = '/home/juan/projects/lab/incflow/tests/dfg2d2_points.csv';
delimiter = ' ';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
time = dataArray{:, 1};
drag = dataArray{:, 2};
lift = dataArray{:, 3};
pdiff = dataArray{:, 4};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

time0 = 0.0;
eps = 8.0;
time1 = time0 + eps;

idx = (time >= time0) & (time <= time1);

min_drag = min(drag(idx));
max_drag = max(drag(idx));
mean_drag = mean(drag(idx));

amp_drag = max_drag - min_drag;

min_lift = min(lift(idx));
max_lift = max(lift(idx));
mean_lift = mean(lift(idx));

amp_lift = max_lift - min_lift;

figure;
subplot(3,1,1);
plot(time(idx), lift(idx));
ylabel('C_L');
xlabel('t');
title('Lift');

subplot(3,1,2);
plot(time(idx), drag(idx));
ylabel('C_D');
xlabel('t');
title('Drag');

subplot(3,1,3);
plot(time(idx), pdiff(idx));
ylabel('\Delta P');
xlabel('t');
title('Pressure difference');